### PR TITLE
Allocate SystemDefaultCharSize instead of 1 byte per char for buffer used in WinGLNative.HandleDropFiles

### LINKED ISSUE #626: Win32 exception 0xc0000374 occurs randomly FileDrop event
### Description

Program randomly, but frequently, crashes with a Win32 exception code 0xc0000374 when the OnFileDrop ( or event handler ) method is called.

### Repro steps

```
using ( var window = new GameWindow() )
{
      window.FileDrop += (s, e) => { };
      window.Run();
}
```

Using the above snippit, drop a file on the window a handful of times and it will eventually crash.

### Expected behavior

Shouldn't crash. Exception also can't be caught ( or at least through any normal means ).

### Actual behavior

Inevitable crash of the program.

### Related information 

Windows 10
Native GL
Built from source today.
.NET Framework

### PR DESCRIPTION
**Pull request by UnknownShadow200**
DragQueryFile returns number of characters. Previously, a buffer of 'number of characters' bytes was being allocated.

This change fixes crashing when the platform uses a character set with more than one byte per character. (unicode charset has 2 bytes)

Fixes #626

### CODE REVIEW

File: src/OpenTK/Platform/Windows/WinGLNative.cs [hunk 1]
```diff
@@ -692,10 +692,11 @@ private void HandleDropFiles(IntPtr handle, WindowMessage message, IntPtr wParam
             for (uint i = 0; i < filesCounter; ++i)
             {
                 // Don't forget about \0 at the end
-                uint fileNameSize = Functions.DragQueryFile(hDrop, i, IntPtr.Zero, 0) + 1;
-                IntPtr str = Marshal.AllocHGlobal((int)fileNameSize);
+                uint filenameChars = Functions.DragQueryFile(hDrop, i, IntPtr.Zero, 0) + 1;
+                int filenameSize = (int)(filenameChars * 2); // for unicode char set, 2 bytes per character
```
Comment (VPeruS) [inline src/OpenTK/Platform/Windows/WinGLNative.cs]: unicode require 4 byte for char

**Comment by Frassle** [comment]
Minor as we'll probably go fully uncoded soon but would be better to use Marshal.SystemDefaultCharSize rather than always using two.

**Comment by Nihlus** [comment]
I agree with @Frassle - whenever possible, use a known value.

**Comment by VPeruS** [comment]
I suppouse free call can be placed after PtrToStringAuto

**Comment by UnknownShadow200** [comment]
Nice catch. I wasn't aware that field even existed.

(And yeah, UCS-2 would have been better - but is irrelevant now)
