### PR TITLE
Fix leaking Cocoa Machports on macOS

### LINKED ISSUE #407: Leaking of Mach Ports on OS X
I have recently come across an issue on OS X, where creating and destroying an OpenGL context is leaking mach ports. This issue can reliably be reproduced with one of the following methods (with the second method just being a more refined version of the first).

```
void machLeak1() {
  while(true) {
    (new GameWindow()).Dispose();
  }
}

void machLeak2() {
  OpenTK.Toolkit.Init();
  var wi = OpenTK.Platform.Utilities.CreateMacOSWindowInfo(IntPtr.Zero);
  while(true) {
    var context = new OpenTK.GraphicsContext(OpenTK.Graphics.GraphicsMode.Default, wi);
    context.MakeCurrent(wi);
    context.Dispose();
  }
}
```

If you run one of these pieces of code and watch the "Ports" column in Activity Monitor for the process, you can see the number of ports increases unbounded as the code runs, until it crashes with either an `OpenTK.GraphicsException` "Failed to construct NSOpenGLContext", or sometimes with a native crash, such as [Mach_Port_Leak_Crash.txt](https://github.com/opentk/opentk/files/336077/Mach_Port_Leak_Crash.txt) or [Mach_Port_Leak_Crash2.txt](https://github.com/opentk/opentk/files/336078/Mach_Port_Leak_Crash2.txt).

I did some counting of iterations, and it works out that 2 mach ports are being leaked for ever iteration in one of the above loops. It will also crash after about 750 iterations.

It really just looks like something is forgotten to be released, but I'm not familiar enough with the low-level API here to know specifically how to fix this problem.

Also, here is my system setup:
OS X 10.11.3
OpenTK master (01e0027580f5930083da40ea43e5721654efd837)
Mono 4.4.0
Xamarin Studio 5.10.3

### PR DESCRIPTION
**Pull request by Nihlus**
This PR implements the discussed fix for leaking Machports on macOS. The main discussion of this problem was held in issue #407, and the included fix was shown to alleviate the problem.

The most substantial change is the introduction of a new helper class for Cocoa which mimicks the behaviour and usage of an [NSAutoreleasePool] (https://developer.apple.com/documentation/foundation/nsautoreleasepool) block in objective-C. The new NSAutoreleasePool class can be utilized with C# `using` statements to form similar nested stack-based pool constructs as is usually done in objective-C.

This construct has then been applied to the disposal method of CocoaContext, wherein the mach ports were being created but not successfully released. By wrapping the Cocoa functions therein with one of these pools, the mach ports are successfully released.

It is likely that the lack of these pools are the source of other hitherto unknown memory-related issues on macOS, but for now, this fix is sufficient to close #407.

### CODE REVIEW

File: src/OpenTK/Platform/MacOS/Cocoa/NSAutoreleasePool.cs [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+    {
+        private readonly IntPtr _autoreleasePool;
+
+        /// <summary>
+        /// Allocates and initializes a new <see cref="NSAutoreleasePool"/>.
+        /// </summary>
+        public NSAutoreleasePool()
+        {
+            _autoreleasePool = Cocoa.SendIntPtr(Class.NSAutoreleasePool, Selector.Get("alloc"));
+            _autoreleasePool = Cocoa.SendIntPtr(_autoreleasePool, Selector.Get("init"));
```
Comment (Frassle) [inline src/OpenTK/Platform/MacOS/Cocoa/NSAutoreleasePool.cs]: Repeat assignment is a little odd here. Separate var for the first alloc call?
Also you can reuse init and alloc selectors from Selector.

File: src/OpenTK/Platform/MacOS/CocoaContext.cs [hunk 2]
```diff
@@ -340,17 +340,23 @@ protected override void Dispose(bool disposing)
...
             Debug.Print("Disposing of Cocoa context.");
 
-            if (!NSApplication.IsUIThread)
+            using (var pool = new NSAutoreleasePool())
             {
-                return;
-            }
+                if (!NSApplication.IsUIThread)
+                {
+                    return;
```
Comment (Frassle) [inline src/OpenTK/Platform/MacOS/CocoaContext.cs]: Early return can be before the using block?

File: src/OpenTK/Platform/MacOS/Cocoa/NSAutoreleasePool.cs (hunk 1 above)
Comment (Nihlus) [inline src/OpenTK/Platform/MacOS/Cocoa/NSAutoreleasePool.cs]: Yep, that's reasonable.

File: src/OpenTK/Platform/MacOS/Cocoa/NSAutoreleasePool.cs [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+        /// </summary>
+        public void Dispose()
+        {
+            if (_autoreleasePool != IntPtr.Zero)
+            {
+                Cocoa.SendVoid(_autoreleasePool, Selector.Get("drain"));
+            }
+        }
+    }
+}
```
Comment (VPeruS) [inline src/OpenTK/Platform/MacOS/Cocoa/NSAutoreleasePool.cs]: Why github complain about missing newline at the end of file?

Comment (Nihlus) [inline src/OpenTK/Platform/MacOS/Cocoa/NSAutoreleasePool.cs]: It's a definition from the POSIX standard of text files. However, it's not strictly required.

**Comment by Frassle** [comment]
LGTM
